# Video
vo=gpu-next
hwdec=auto-safe
gpu-api=vulkan

# Audio
audio-channels=stereo
volume=80
volume-max=150

# Subtitles
sub-auto=fuzzy
sub-font="UDEV Gothic 35NFLG"
sub-font-size=44
sub-color="#cdd6f4"
sub-border-color="#1e1e2e"
sub-border-size=2
sub-shadow-color="#00000088"
sub-shadow-offset=1

# UI
osd-font="UDEV Gothic 35NFLG"
osd-font-size=32
osd-color="#cdd6f4"
osd-border-color="#1e1e2e"
osd-bar-h=2
keep-open=yes
save-position-on-quit=yes

# Screenshot
screenshot-format=png
screenshot-directory=~/Pictures/screenshots
screenshot-template="%F_%P"
