search_mode = "fuzzy"
filter_mode = "global"
workspaces = true

style = "compact"
inline_height = 20
show_preview = true
enter_accept = true
keymap_mode = "auto"

history_filter = [
  "^\\s*rm -rf",
  "^\\s*sudo rm",
]

[stats]
common_subcommands = [
  "cargo",
  "docker",
  "git",
  "go",
  "kubectl",
  "npm",
  "systemctl",
  "yay",
]

[sync]
records = true

[ui]
columns = ["duration", "directory", "command"]
