shell = "zsh"

[plugins.zsh-completions]
github = "zsh-users/zsh-completions"

# fzf-tab must be loaded after compinit but before plugins that wrap widgets
# (zsh-autosuggestions / fast-syntax-highlighting).
[plugins.fzf-tab]
github = "Aloxaf/fzf-tab"

[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"

[plugins.zsh-vi-mode]
github = "jeffreytse/zsh-vi-mode"

[plugins.zsh-autopair]
github = "hlissner/zsh-autopair"

[plugins.you-should-use]
github = "MichaelAquilina/zsh-you-should-use"

[plugins.fast-syntax-highlighting]
github = "zdharma-continuum/fast-syntax-highlighting"
