hl.on("hyprland.start", function()
    hl.exec_cmd("waybar")
    hl.exec_cmd("cliphist wipe")
    hl.exec_cmd("~/.config/hypr/wallpaper.sh")
    hl.exec_cmd("wl-paste --type text --watch ~/.config/hypr/cliphist_filter.sh")
    hl.exec_cmd("wl-paste --type image --watch cliphist store")
    hl.exec_cmd("systemctl --user start hypridle.service")
    hl.exec_cmd("systemctl --user start hyprpaper.service")
    hl.exec_cmd("systemctl --user start hyprpolkitagent.service")
end)
