#############
### INPUT ###
#############

# https://wiki.hyprland.org/Configuring/Variables/#input
input {
    kb_layout = us
    kb_variant =
    kb_model =
    kb_options =
    kb_rules =

    follow_mouse = 1

    sensitivity = 0.2 # カーソル速度調整（-1.0 - 1.0）

    accel_profile = adaptive  # デフォルトに戻す（flatは遅くなる）
    repeat_rate = 50     # キーリピート高速化
    repeat_delay = 400   # リピート開始遅延短縮

    touchpad {
        natural_scroll = false
    }
}


# Example per-device config
# See https://wiki.hyprland.org/Configuring/Keywords/#per-device-input-configs for more
device {
    name =ergo-m575sp-mouse
    sensitivity = 0.7
}
device {
    name =logi-m240-mouse
    sensitivity = 0.7
}
device {
    name=protoarc-em01-mouse
    sensitivity = -0.3
}
