
[terminal.shell]
program = "fish"
args = ["-l","-c","zellij"]

[cursor]
style = "Block"
unfocused_hollow = true

[env]
TERM = "xterm-256color"

[font]
size = 14.0

[font.bold]
family = "monospace"
style = "Bold"

[font.italic]
family = "monospace"
style = "Italic"

[font.normal]
family = "monospace"
style = "Regular"

[mouse]
hide_when_typing = false

[[mouse.bindings]]
action = "PasteSelection"
mouse = "Middle"

[scrolling]
history = 10000
multiplier = 3

[selection]
save_to_clipboard = false
semantic_escape_chars = ",│`|:\"' ()[]{}<>"

[window]
decorations = "full"
dynamic_padding = false
dynamic_title = true

[keyboard]

bindings = [
  {key = "V", mods = "Control|Shift", action = "Paste"},
  {key = "C", mods = "Control|Shift", action = "Copy"},
  {key = "Q", mode="Vi|~Search",      action="ToggleViMode"},
]

[general]
live_config_reload = true

import = [
  "~/.config/alacritty/solarized.toml",
]

[terminal]


